<div class="block">
    <h2 class="title">Phân quyền nhóm Người Dùng</h2>
    <div class="block-content">
    Thành viên hệ thống gồm 3 cấp:
        <br/>
        + Quản trị: Trưởng Ban Tổ chức, PBT Khối Xây Dựng Đoàn  người có toàn quyền với hệ thồng
        <br/>
        + Cán bộ quản lý: cán bộ Ban Tổ Chức được cấp quyền thao tác về nghiệp vụ với hệ thống
        <br/>
        + Cán bộ: cán bộ được quản lý, có quyền xem thông tin của bản thân và gửi kiến nghị nếu có sai sót.
    </div>
</div>