<div class="block">
    <h2 class="title">Đổi mật khẩu</h2>
    <div class="block-content">
        <fieldset>
            <legend>Đổi mật khẩu</legend>
            <div class="content">
                <form method="post">
                    <div>
                        <div>Tài khoản: <td><?=$this->user['Username']?></td> </div>
                        <div>Vai trò: <?=$this->user['Role_Display_Name']?></div>
                        <div>Cán bộ: <?=$this->user['Ho_Ten_CB']?></div>
                        <div>Ngày sinh: <?=$this->user['Ngay_Sinh']?></div>
                        <div>CMND: <?=$this->user['So_CMND']?></div>
                    </div>
                    <hr>
                    <div>
                       <!-- <span><strong>Thay đổi tên đăng nhập: </strong></span>
                       <input class="password" type="text" id='username' name="username" size='30' required="required" value="<?=$this->user['Username']?>" /><br/>
                       <hr> -->
                       <span>Mật khẩu mới: </span>
                       <input class="password" type="password" id='password_new' name="password_new" size='30' required="required"/> (*) Chú ý: Mật khẩu sẽ được mã hóa.<br/>
                       <span>Xác nhận Mật khẩu mới: </span>
                       <input class="password" type="password" id='re_password' name="re_password" size='30' required="required"/> (*) Chú ý: Nhập đúng mật khẩu mới bên trên.<br/>

                       <span> <button type="submit" id="change-pass">Đổi mật khẩu</button> </span>
                    </div>


                </form>
                <p>
                <mark> <?php echo $this->message?> <mark>
                </p>
            </div>
        </fieldset>
    </div>
</div>

<script>
    $("#change-pass").click(function(){
        //show message box (OK/Cancel)
        var messageValue = confirm("Xác nhận đổi mật khẩu?");
        if(messageValue){
            if($('#password_new').val()!=$('#re_password').val()){
                alert('Xác nhận mật khẩu không khớp với mật khẩu mới');
                return false;
            }
            return true;
        }else{
            return false;//Cancel submit
        }
    })

</script>