<style type="text/css" title="currentStyle">
    @import "/script/datatable/media/css/demo_page.css";
    @import "/script/datatable/media/css/demo_table.css";
    @import "/script/datatable/extras/TableTools/media/css/TableTools.css";
    @import "/script/datatable/extras/ColReorder/media/css/ColReorder.css";
    thead input { width: 100% }
    input.search_init { color: #999 }
</style>

<div class="block">
    <h2 class="title">Thông tin người dùng</h2>
    <div class="block-content">
        <fieldset>
            <legend>Danh sách người dùng, cán bộ</legend>
            <div class="content">
                <table cellpadding="0" cellspacing="0" border="0" class="display" id="thongtincanbo">
                    <thead>
                    <tr>
                        <td><input type="text" value="" class="search_init" /></td>
                        <td><input type="text" value="" class="search_init" /></td>
                        <td><input type="text" value="" class="search_init" /></td>
                        <td></td>
                        <td></td>
                        <td style="width: 80px !important;"></td>
                    </tr>
                    <tr>
                        <th>Username</th>
                        <th>Giữ vai trò</th>
                        <th>Họ tên Cán Bộ</th>
                        <th>Ngày sinh</th>
                        <th>CMND</th>
                        <th>Công cụ</th>
                    </tr>

                    </thead>
                    <?php
                    if($this->dsUser){
                        foreach($this->dsUser as $element){
                            echo '<tr>
                                        <td>',$element['Username'], '</td>
                                        <td>',$element['Role_Display_Name'], '</td>
                                        <td>',$element['Ho_Ten_CB'], '</td>
                                        <td>',$element['Ngay_Sinh'], '</td>
                                        <td>',$element['So_CMND'], '</td>
                                        <td>
                                            <a href="authorization/' . $element['UserID'] . '" class="edit" title="Sửa quyền"></a>
                                            <a href="change-password/' . $element['UserID'] . '" class="changepassbutton" title="Đổi mật khẩu"></a>
                                            <a href="voiddelete/' . $element['UserID'] . '" class="voiddeletebutton" title="Xóa cán bộ"></a>
                                        </td>
                                  </tr>';
                        }
                    }
                    ?>
                </table>
                <div class="clear"></div>

            </div>
        </fieldset>
    </div>
</div>
<script>
    $(document).ready( function () {
        var oTable;

        /* Add the events etc before DataTables hides a column */
        $("thead input").keyup( function () {
            /* Filter on the column (the index) of this element */
            oTable.fnFilter( this.value, oTable.oApi._fnVisibleToColumnIndex(
                oTable.fnSettings(), $("thead input").index(this) ) );
        } );

        /*
         * Support functions to provide a little bit of 'user friendlyness' to the textboxes
         */
        $("thead input").each( function (i) {
            this.initVal = this.value;
        } );

        $("thead input").focus( function () {
            if ( this.className == "search_init" )
            {
                this.className = "";
                this.value = "";
            }
        } );

        $("thead input").blur( function (i) {
            if ( this.value == "" )
            {
                this.className = "search_init";
                this.value = this.initVal;
            }
        } );

        oTable = $('#thongtincanbo').dataTable( {
            "sDom": 'T<"clear">lfrtip',
            "oTableTools": {
                "sSwfPath": "/script/datatable/extras/TableTools/media/swf/copy_cvs_xls_pdf.swf",
                "aButtons": [

                ]
            }
            //"sPaginationType": "full_numbers"
        } );
    } );
</script>


