<style>
    .custom-combobox {
        position: relative;
        display: inline-block;
        margin-right: 30px;
    }
    .custom-combobox-toggle {
        position: absolute;
        top: 0;
        bottom: 0;
        margin-left: -1px;
        padding: 0;
        /* support: IE7 */
        *height: 1.7em;
        *top: 0.1em;
    }
    .custom-combobox-input {
        margin: 0;
        padding: 0.3em;
    }

    .ui-autocomplete {
        max-height: 100px;
        overflow-y: auto;
        overflow-x: hidden;
    }

</style>
<script type="text/javascript" src="/script/datatable/jquery.dataTables.min.js"></script>
<style type="text/css" src="/script/datatable/jquery.dataTables.min.css"></style>

<div class="block">
    <h2 class="title">Danh sách ban</h2>
    <div class="block-content">
        <fieldset>
            <legend>Tạo mới phòng ban</legend>
            <form method="post">
                <span>Nhập tên phòng ban mới</span>
                <input type="text" name="ten_ban" value="" placeholder="Ban Văn Phòng"><br>
                <button type="submit" class="changelable-submitbutton">Tạo thêm Phòng/Ban</button>
            </form>
        </fieldset>
        <br>
        <fieldset>
            <legend>Danh sách các phòng/ban hiện tại - nhấp vào để thay đổi</legend>
            <div class="content">
                <div class="block-content" id="js-hire-tree">
                <table id="thanhvien">
                   <thead>
                    <tr>
                        <th>Họ tên</th>
                        <th>Ngày sinh</th>
                        <th>Chức vụ</th>
                        <th>Đơn vị</th>
                        <th>Thao tác</th>
                    </tr>

                    </thead>
                    <?php
                    if($this->dsCanBo){
                        foreach($this->dsCanBo as $element){
                            echo '<tr>
                                        <td>',$element['Ho_Ten_CB'], '</td>
                                        <td>',$element['Ngay_Sinh'], '</td>
                                        <td>',$element['Ten_Chuc_Vu'], '</td>
                                        <td>',$element['Ten_Đon_Vi'], '</td>
                                        <td>
                                            <a href="lylich/' . $element['Ma_Can_Bo'] . '" class="view" title="Xem lý lịch"></a>
                                        </td>
                                      </tr>';
                        }
                    }
                    ?>
                </table>
                </div>
            </div>
        </fieldset>
    </div>
</div>

<link rel="stylesheet" href="/script/themes/default/style.min.css" type="text/css">