<?php
    $templateURL = $this->basePath('template/');

?>
<!DOCTYPE html>
<html>
<head>
    <title>Hệ thống quản lý cán bộ TPHCM</title>
    <script src="<?php echo $templateURL;?>js/jquery-1.9.1.js"></script>
    <script src="<?php echo $templateURL;?>js/jqueryui/js/jquery-ui-1.10.3.custom.js"></script>
        <link rel="stylesheet" href="<?php echo $templateURL;?>js/font-awesome/css/font-awesome.min.css" type="text/css">

    <?php echo $this->headScript() ?>
    <?php echo $this->headStyle() ?>
    <?php $uri = $this->serverUrl(true); ?>

    <link rel="stylesheet" href="<?php echo $templateURL;?>js/jqueryui/css/qlcbd-theme/jquery-ui-1.10.3.custom.css" type="text/css">
    <link rel="stylesheet" href="<?php echo $templateURL;?>css/style.css" type="text/css">

</head>
<body>
    <div id="loading"></div>
    <!--Header-->
    <div id="header">
        <div class="content">
            <div class="title">
                <a class="logo" href="<?php echo $this->basePath(); ?>">Hệ thống Quản lý cán bộ</a>
            </div>
            <div class="navigation">
                <ul class="menu">
                    <li class="first"><a href="<?php echo $this->basePath('application/user/account'); ?>">Tài khoản: <?=(new \Zend\Authentication\AuthenticationService)->getIdentity()->Username?></a></li>
                    <li class="last"><a href="<?php echo $this->basePath('application/user/logout'); ?>">Đăng xuất</a></li>
                </ul>
            </div>
            <ul class="submenu">
                <?php
                if ((new \Zend\Authentication\AuthenticationService)->getIdentity()->Role_Name == 'manager' | (new \Zend\Authentication\AuthenticationService)->getIdentity()->Role_Name == 'admin')
                {
                    ?>
                    <li  class="<?php if(strpos($uri, 'cadre/canbo')) echo 'active-submenu'; ?>">
                        <a href="<?php echo $this->basePath('cadre/canbo'); ?>" title="Dành cho cán bộ thông thường">Tài khoản sử dụng</a>
                    </li>
                    <li  class="<?php if(strpos($uri, 'manager')) echo 'active-submenu'; ?>">
                        <a href="<?php echo $this->basePath('manager'); ?>" title="Dành cho cán bộ Ban tổ chức">Quản lý cán bộ</a>
                    </li>
                <?php
                }

                if ((new \Zend\Authentication\AuthenticationService)->getIdentity()->Role_Name == 'admin'): ?>
                    <li  class="<?php if(strpos($uri, 'admin')) echo 'active-submenu'; ?>">
                        <a href="<?php echo $this->basePath('admin'); ?>" title="Dành cho cán bộ Quản trị hệ thống">Quản trị cao cấp</a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
    <!--End header-->
    <!--Wrapper-->
    <div id="wrapper">
        <div class="content">
            <div class="sidebar">
                <div class="item main-menu">
                    <h3 class="title"><i class="fa fa-home"></i> Trình đơn chính</h3>
                    <div class="itemContent">
                        <ul class="menu">
                            <li><a href="<?php echo $this->basePath('manager'); ?>">Trang chủ</a></li>
                            <li><a href="<?php echo $this->basePath('manager/canbo'); ?>">Quản lý cán bộ</a>
                                <ul class="<?php if(strpos($uri, 'manager/canbo')) echo 'active-menu-ul'; ?>">
                                    <li><a href="<?php echo $this->basePath('manager/canbo/thongtin'); ?>">Thông tin cán bộ</a></li>
                                    <!-- <li><a href="<?php echo $this->basePath('manager/canbo/danhgia'); ?>">Đánh giá cán bộ</a></li> -->
                                    <!-- <li><a href="<?php echo $this->basePath('manager/canbo/luanchuyen'); ?>">Luân chuyển cán bộ</a></li>
                                    <li><a href="<?php echo $this->basePath('manager/canbo/luong'); ?>">Lương cán bộ</a></li>
                                    <li><a href="<?php echo $this->basePath('manager/canbo/congtacnuocngoai'); ?>">Đi nước ngoài</a></li> -->
                                    <li><a href="<?php echo $this->basePath('manager/canbo/giaiquyetkiennghi'); ?>">Phản hồi kiến nghị</a></li>
                                    <li><a href="<?php echo $this->basePath('manager/canbo/canbocu'); ?>">Cựu cán bộ</a></li>
                                </ul>
                            </li>
                            <?php
                                if ((new \Zend\Authentication\AuthenticationService)->getIdentity()->Role_Name == 'admin')
                                {
                                ?>
                            <li><a href="<?php echo $this->basePath('manager/cocau'); ?>">Quản lý cơ cấu</a>
                                <ul class="<?php if(strpos($uri, 'manager/cocau')) echo 'active-menu-ul'; ?>">
                                    <!-- <li><a href="<?php echo $this->basePath('manager/cocau/thanhlapdonvi'); ?>">Đơn vị</a></li> -->
                                    <!-- <li><a href="<?php echo $this->basePath('manager/cocau/thanhlapbch'); ?>">Ban chấp hành</a></li> -->
                                    <li><a href="<?php echo $this->basePath('manager/cocau/thanhlapphongban'); ?>">Phòng ban</a></li><!-- 
                                    <li><a href="<?php echo $this->basePath('manager/cocau/loaihinhban'); ?>">Loại hình ban</a></li>-->
                                    <!--  <li><a href="<?php echo $this->basePath('manager/cocau/tochuccocau'); ?>">Tổ chức cơ cấu</a></li>  -->
                                </ul>
                            </li>

                            <li><a href="<?php echo $this->basePath('manager/search'); ?>">Tra cứu nhanh</a></li>
                            <li><a href="<?php echo $this->basePath('manager/baocao'); ?>">Báo cáo thống kê</a>
                                <ul class="<?php if(strpos($uri, 'manager/baocao')) echo 'active-menu-ul'; ?>">
                                    <li><a href="<?php echo $this->basePath('manager/baocao/truyvan'); ?>">Báo cáo truy vấn</a></li>
                                    <li><a href="<?php echo $this->basePath('manager/baocao/canbo'); ?>">Cán bộ các ban</a></li>
                                    <li><a href="<?php echo $this->basePath('manager/baocao/cannangluong'); ?>">Danh sách nâng lương</a></li>
                                    <li><a href="<?php echo $this->basePath('manager/baocao/lichsudonvi'); ?>">Lịch sử đơn vị</a></li>
                                </ul>
                            </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="main"> 
                <?php echo $this->content; ?>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <!--End wrapper-->
    <!--Footer-->
    <div id="footer">
        <div class="content">
            <div class="author">
                <a class="logo" href="#"></a>
            </div>

            <div class="copyright">
                <p>Hệ thống Quản lý Cán bộ Thành Đoàn TPHCM</p>
                <p>Copyright &#169 2013</p>
                <p>Xây dựng bởi Đoàn trường ĐH Công nghệ Thông tin - ĐHQG-HCM</p>
            </div>

            <div class="clear"></div>
        </div>
    </div>
    <!--End footer-->
    <div id="totopbutton">K
    </div>
    <script src="<?php echo $templateURL;?>js/animation.js"></script>
</body>
</html>