<style type="text/css" title="currentStyle">
    @import "<?php echo ROOT_PATH; ?>public/script/datatable/media/css/demo_page.css";
    @import "<?php echo ROOT_PATH; ?>public/script/datatable/media/css/demo_table.css";
    @import "<?php echo ROOT_PATH; ?>public/script/datatable/extras/TableTools/media/css/TableTools.css";
    @import "<?php echo ROOT_PATH; ?>public/script/datatable/extras/ColReorder/media/css/ColReorder.css";
    thead input { width: 100% }
    .custom-combobox {
        position: relative;
        display: inline-block;
        margin-right: 30px;
    }
    .custom-combobox-toggle {
        position: absolute;
        top: 0;
        bottom: 0;
        margin-left: -1px;
        padding: 0;
        /* support: IE7 */
        *height: 1.7em;
        *top: 0.1em;
    }
    .custom-combobox-input {
        margin: 0;
        padding: 0.3em;
    }

    .ui-autocomplete {
        max-height: 100px;
        overflow-y: auto;
        overflow-x: hidden;
    }

</style>
<script>
    function checkInput(){
        if ($('#begin').val() > $('#end').val()){
            alert('Ngày bắt đầu không lớn hơn ngày kết thúc');
            $('#begin').val($('#end').val());
        }
    }
    function loadTable()
    {
        var oTable;

        /* Add the events etc before DataTables hides a column */
        $("thead input").keyup( function () {
            /* Filter on the column (the index) of this element */
            oTable.fnFilter( this.value, oTable.oApi._fnVisibleToColumnIndex(
                oTable.fnSettings(), $("thead input").index(this) ) );
        } );

        /*
         * Support functions to provide a little bit of 'user friendlyness' to the textboxes
         */
        $("thead input").each( function (i) {
            this.initVal = this.value;
        } );

        $("thead input").focus( function () {
            if ( this.className == "search_init" )
            {
                this.className = "";
                this.value = "";
            }
        } );

        $("thead input").blur( function (i) {
            if ( this.value == "" )
            {
                this.className = "search_init";
                this.value = this.initVal;
            }
        } );

        oTable = $('#logger').dataTable( {
            "sDom": 'T<"clear">lfrtip',
            "oTableTools": {
                "sSwfPath": "<?php echo ROOT_PATH; ?>public/script/datatable/extras/TableTools/media/swf/copy_cvs_xls_pdf.swf",
                "aButtons": [ 'xls' ]
            }
        } );
    }
    function loadData(begin, end){
        $('#loading').fadeIn(300);
        var parameter = '';
        if (begin){
            parameter += '?begin=' + begin + '&end=' + end;
        }
        $.ajax({
            type: "POST",
            url: "<?php echo $this->basePath('admin/log/loadlog'); ?>" + parameter,
            data: "",
            contentType : false,
            processData : false,
            success: function( data )
            {
                var obj = JSON.parse(data);
                console.log(obj);
                var size = obj.length;
                var html = '<table id="logger" cellpadding="0" cellspacing="0" border="0" class="display">';
                html += '<thead>\
                            <tr>\
                                <td><input type="text" class="search_init" /></td>\
                                <td><input type="text" class="search_init" /></td>\
                                <td><input type="text" class="search_init" /></td>\
                                <td><input type="text" class="search_init" /></td>\
                            </tr>\
                            <tr>\
                                <th>Thời gian</th>\
                                <th>Tài khoản</th>\
                                <th>Cán bộ</th>\
                                <th>Nội dung</th>\
                            </tr>\
                        </thead>';
                for (i = 0; i < size; i++){
                    html += '<tr>';
                    html += '<td>' + obj[i].Thoi_Gian + '</td>';
                    html += '<td>' + obj[i].TaiKhoan + '</td>';
                    html += '<td>' + obj[i].HoTen + '</td>';
                    html += '<td>' + obj[i].Noi_Dung + '</td>';
                    html += '</tr>';
                }
                html += '</table>';
                $('#show').html(html);
                loadTable();
                $('#loading').fadeOut(300);
            }
        });
    }
</script>

<div class="block">
    <h2 class="title">Lưu vết người dùng</h2>
    <div class="block-content">
        <fieldset>
            <legend>Chọn khoảng thời gian</legend>
            <div class="content">
                <form onsubmit="return false">
                    Bắt đầu: <input onchange="checkInput()" type="text" class="ngaythang" id="begin" value="<?php echo date('Y-m-d'); ?>" />
                    Kết thúc: <input onchange="checkInput()" type="text" class="ngaythang" id="end" value="<?php echo date('Y-m-d'); ?>" />
                    <br/><button id="view" type="button">Xem lưu vết</button>
                </form>

            </div>
        </fieldset>
        <fieldset>
            <legend>Thông tin</legend>
            <div id="show" class="content">

            </div>
        </fieldset>
    </div>
</div>

<script>
    loadData(false,false);

    $('#view').click(function(){
        var begin   = $('#begin').val();
        var end     = $('#end').val();
        loadData(begin, end);
    });
    $(".ngaythang").datepicker({dateFormat: 'yy-mm-dd'});
</script>