<?php
    $this->data=(new \Zend\Authentication\AuthenticationService)->getIdentity();
?>
<div class="block">
    <div class="block-content">
        <table id="danhsach">
            <tr>
                <td>Tên User</td>
                <td><?php echo $this->data->Username  ?></td>
            </tr>
            <tr>
                <td>Quyền hạn</td>
                <td><?php echo $this->data->Role_Name ?></td>
            </tr>
            <tr>
                <td>Tên cán bộ sở hữu</td>
                <td><?=$this->nameAccountOwn?></td>
            </tr>
            <tr>
                <td>Mật khẩu</td>
                <td> <a>***********</a> <a href="<?php echo $this->basePath('cadre/user/change-password/') . $this->data->UserID; ?>" class="button">Đổi mật khẩu</a></td>
            </tr>
        </table>


    </div>
</div>