<div class="block">
    <h2 class="title">Quản lý Tài khoản</h2>
    <div class="block-content">
        <ul class="metro">
            <li title="Sửa Thông Tin Tài Khoản">
                <a href="<?php echo $this->basePath('cadre/user/account'); ?>">
                    Tài Khoản </br>
                    <span><i class="fa fa-info-circle fa-5x"></i></span>
                </a>
            </li><!-- 
            <li title="Đổi mật khẩu">
                <a href="<?php echo $this->basePath('cadre/user/change-password'); ?>">
                    Đổi Mật Khẩu
                    <span><i class="fa fa-lock fa-5x"></i></span>
                </a>
            </li> -->

        </ul>
    </div>
</div>