<div class="block">
    <h2 class="title">Thông tin cán bộ</h2>
    <div class="block-content">
        <ul class="metro">
            <li>
                Thông tin cán bộ
                <span class="icon"></span>
            </li>
            <li>
                Quản lý cơ cấu
                <span class="icon structure"></span>
            </li>
            <li>
                Đánh giá cán bộ
                <span class="icon rating"></span>
            </li>
            <li>
                Tra cứu
                <span class="icon search"></span>
            </li>
            <li>
                Báo cáo thống kê
                <span class="icon statistic"></span>
            </li>
        </ul>
    </div>
</div>