<div class="block">
    <h2 class="title">Quản lý cơ cấu</h2>
    <div class="block-content">
        <ul class="metro"> 
            <li title="Tạo đơn vị mới">
                <a href="<?php echo $this->basePath('manager/cocau/thanhlapdonvi'); ?>">
                    Đơn vị</br>
                    <span><i class="fa fa-flag fa-5x"></i></span>
                </a>
            </li><!-- 
            <li title="Tạo Ban chấp hành mới">
                <a href="<?php echo $this->basePath('manager/cocau/thanhlapbch'); ?>">
                    Ban chấp hành
                    <span><i class="fa fa-group fa-5x"></i></span>
                </a>
            </li> -->
            <li title="Tạo phòng ban mới">
                <a href="<?php echo $this->basePath('manager/cocau/thanhlapphongban'); ?>">
                    Phòng Ban </br>
                    <span><i class="fa fa-building fa-5x"></i></span>
                </a>
            </li><!-- 
            <li title="Tạo loại hình phòng ban mới">
                <a href="<?php echo $this->basePath('manager/cocau/loaihinhban'); ?>">
                    Loại hình ban
                    <span><i class="fa fa-sitemap fa-5x"></i></span>
                </a>
            </li> -->
            <li title="Quản lý tổ chức cơ cấu">
                <a href="<?php echo $this->basePath('manager/cocau/tochuccocau'); ?>">
                    Tổ chức cơ cấu
                    <span><i class="fa fa-share-alt fa-5x"></i></span>
                </a>
            </li> 
        </ul>
    </div>
</div>