<div class="block">
    <h2 class="title">Thông tin đơn vị</h2>
    <div class="block-content">
        <table id="danhsach">
            <tr>
                <td>Tên đơn vị</td>
                <td><?php echo $this->data['Ten_Đon_Vi'] ?></td>
            </tr>
            <tr>
                <td>Ngày thành lập</td>
                <td><?php echo $this->data['Ngay_Thanh_Lap'] ?></td>
            </tr>
            <tr>
                <td>Chức năng đơn vị</td>
                <td><?php echo $this->data['Chuc_Nang_ĐV'] ?></td>
            </tr>
            <tr>
                <td>Địa chỉ</td>
                <td><?php echo $this->data['Đia_Chi'] ?></td>
            </tr>
            <tr>
                <td>Email</td>
                <td><?php echo $this->data['Email'] ?></td>
            </tr>
            <tr>
                <td>Điện thoại</td>
                <td><?php echo $this->data['So_Đien_Thoai'] ?></td>
            </tr>
            <tr>
                <td>Mô tả</td>
                <td><?php echo $this->data['Mo_Ta'] ?></td>
            </tr>
        </table>
        <button type="button" onclick="tableToExcel('danhsach', 'Download')">Xuất thông tin</button>
        <a href="<?php echo $this->basePath('manager/cocau/chinhsuadonvi/') . $this->data['Ma_ĐV']; ?>" class="button">Chỉnh sửa thông tin</a>
        <a href="<?php echo $this->basePath('manager/cocau/thanhlapdonvi/'); ?>" class="button">Xem danh sách đơn vị</a>
    </div>
</div>