<div class="block">
    <h2 class="title">Báo cáo thống kê</h2>
    <div class="block-content">
        <ul class="metro">
            <li title="Tạo báo cáo với dữ liệu tùy chỉnh">
                <a href="<?php echo $this->basePath('manager/baocao/truyvan'); ?>">
                    Báo cáo truy vấn
                    <span><i class="fa fa-file-text fa-5x"></i></span>
                </a>
            </li>
            <!-- <li title="Thống kê danh sách cán bộ các ban, trung tâm thành Đoàn" class="disable">
                <a href="<?php echo $this->basePath('manager/baocao/canbo'); ?>">
                    Cán bộ các ban
                    <span><i class="fa fa-group fa-5x"></i></span>
                </a>
            </li> -->
            <li title="Danh sách cán bộ cần nâng lương theo ngày xét">
                <a href="<?php echo $this->basePath('manager/baocao/cannangluong'); ?>">
                    DS Nâng Lương
                    <span><i class="fa fa-upload fa-5x"></i></span>
                </a>
            </li>
            <!-- <li title="Xem lịch sử sử dụng cán bộ của đơn vị">
                <a href="<?php echo $this->basePath('manager/baocao/lichsudonvi'); ?>">
                    Lịch sử đơn vị
                    <span><i class="fa fa-history fa-5x"></i></span>
                </a>
            </li> -->
        </ul>
    </div>
</div>