<style>
    .custom-combobox {
        position: relative;
        display: inline-block;
        margin-right: 30px;
    }
    .custom-combobox-toggle {
        position: absolute;
        top: 0;
        bottom: 0;
        margin-left: -1px;
        padding: 0;
        /* support: IE7 */
        *height: 1.7em;
        *top: 0.1em;
    }
    .custom-combobox-input {
        margin: 0;
        padding: 0.3em;
    }

    .ui-autocomplete {
        max-height: 100px;
        overflow-y: auto;
        overflow-x: hidden;
    }

</style>

<div class="block" xmlns="http://www.w3.org/1999/html">
    <h2 class="title">Đánh giá cán bộ</h2>

    <div class="block-content">
        <form id ='danhgia' method="post">
            Ngày đánh giá: <input type="text" id="ngaydanhgia" class ='ngaythang' name="ngaydanhgia"  value="<?php echo date('d/m/Y'); ?>"/>
            <fieldset>
                <legend>I. Nội dung Tự nhận xét, đánh giá</legend>
                <div class="group">
                    <span>Đợt đánh giá</span>
                    <select name="dot_danh_gia" id="dot_danh_gia">
                        <?php foreach ($listDot as $key => $value): ?>
                            <option value="<?php echo $value['id']?>"><?php echo $value['name']?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="clear"></div>
                Xếp lọai tự đánh giá:<br/>
                <?php
                    foreach($this->mucdohoanthanh as $element)
                    echo '<label><input type="radio" name="mdht_tdg" value="',$element['Ma_MĐHT'],'" />',$element['Ten_MĐHT'],'</label><br/>';
                ?>
                <?php if(isset($message)) echo $message ?>
                <br/>

            <button type="submit">Lưu Đánh giá</button>
        </form>
    </div>
</div>

<script>
jQuery(document).ready(function($) {
    $(".ngaythang").datepicker({dateFormat: 'dd/mm/yy'});
    $("#dot_danh_gia").change(function(event) {
        loadData()
    });
    loadData()
    function loadData() {
        dotdanhgia = $("#dot_danh_gia").val();
        canbo_tdgID = <?php echo $canboID?>;
        $.ajax({
            url: '<?php echo $this->basePath('manager/canbo/danhgianam'); ?>',
            type: 'POST',
            dataType: 'json',
            data: {canbo_tdgID: canbo_tdgID,dotdanhgia:dotdanhgia},
        })
        .done(function(data) {
            console.log(data.xeploai)
            if(data.xeploai != null){
				$("input[name=mdht_tdg][value=" + data.xeploai + "]").attr('checked', 'checked');
				$("input[name=mdht_tdg]").attr('disabled', true);
            }
        }) 
    }
    
});
    
</script>