<div class="block">
    <h2 class="title">Công tác</h2>
    <div class="block-content">
        <ul class="metro">
            <li title="Đánh giá/ Tự đánh giá">
                <a href="<?php echo $this->basePath('cadre/canbo/danhgia'); ?>">
                    Đánh giá</br>
                    <span><i class="fa fa-star fa-5x"></i></span>
                </a>
            </li>
            <li title=" Đưa kiến nghị, đề xuất với thành đoàn">
                <a href="<?php echo $this->basePath('cadre/canbo/kiennghi'); ?>">
                    Kiến nghị, Đề xuất
                    <span><i class="fa fa-envelope-o fa-5x"></i></span>
                </a>
            </li>
            <!-- <li title=" Xem thông tin cán bộ cấp dưới">
                <a href="<?php echo $this->basePath('cadre/canbo/qlcbcapduoi'); ?>">
                    Cán bộ cấp dưới
                    <span><i class="fa fa-group fa-5x"></i></span>
                </a>
            </li> -->

        </ul>
    </div>
</div>