<style>
    .custom-combobox {
        position: relative;
        display: inline-block;
        margin-right: 30px;
    }
    .custom-combobox-toggle {
        position: absolute;
        top: 0;
        bottom: 0;
        margin-left: -1px;
        padding: 0;
        /* support: IE7 */
        *height: 1.7em;
        *top: 0.1em;
    }
    .custom-combobox-input {
        margin: 0;
        padding: 0.3em;
    }

    .ui-autocomplete {
        max-height: 100px;
        overflow-y: auto;
        overflow-x: hidden;
    }

</style>

<div class="block" xmlns="http://www.w3.org/1999/html">
    <h2 class="title">Đánh giá cán bộ</h2>

    <div class="block-content">
        <form id ='danhgia' method="post">
            Ngày đánh giá: <input type="text" id="ngaydanhgia" class ='ngaythang' name="ngaydanhgia"  value="<?php echo date('d/m/Y'); ?>"/>
            <fieldset>
                <legend>I. Nội dung Tự nhận xét, đánh giá</legend>
                <div class="group">
                    <span>Đợt đánh giá</span>
                    <select name="dot_danh_gia" id="dot_danh_gia">
                        <?php foreach ($listDot as $key => $value): ?>
                            <option value="<?php echo $value['id']?>"><?php echo $value['name']?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="clear"></div>
                <div class="group">
                    <span>Cán bộ tự đánh giá</span>
                    <input type="text" name="hoten_tdg" readonly='readonly' value= "<?php echo $this->canbo_tdg['Ho_Ten_CB']; ?>" />
                </div>
                <div class="clear"></div>

                <div class="group">
                    <span>Ngày sinh</span>
                    <input type="text" name="ngaysinh_tdg" readonly='readonly' disabled='disabled' value= "<?php echo $this->canbo_tdg['Ngay_Sinh']; ?>" />
                </div>
                <div class="clear"></div>

                <div class="group">
                    <span>CMND</span>
                    <input type="text" name="cmnd_tdg" readonly='readonly' disabled='disabled' value= "<?php echo $this->canbo_tdg['So_CMND']; ?>" />
                </div>

                <div class="clear"></div>
                Xếp lọai tự đánh giá:<br/>
                <?php
                    foreach($this->mucdohoanthanh as $element)
                    echo '<label><input type="radio"  class="hoanthanh" id="tudanhgia',$element['Ma_MĐHT'],'" disabled value="',$element['Ma_MĐHT'],'" />',$element['Ten_MĐHT'],'</label><br/>'
                ?>
                <br/>
                <div class="clear"></div>
                <!--
                <div class="group">
                    <span>Chức vụ</span>
                    <input type="hidden" name="chucvu_tdg" readonly='readonly' disabled='disabled' value="" />
                </div>-->
                <div class="clear"></div>
                Ưu điểm khuyết điểm: </br>
                <textarea name="noi_dung_danh_gia" id="noi_dung_danh_gia" placeholder="Ưu khuyết điểm"></textarea>
                <br/>
                <div class="clear"></div>
                Lưu ý: </br>
                <textarea name="luu_y" id="luu_y" placeholder="Lưu ý"></textarea>
                <br/>
                Xếp lọai Cấp trên đánh giá:<br/>
                <?php
                    foreach($this->mucdohoanthanh as $element)
                    echo '<label><input type="radio" name="mdht_tdg" class="hoanthanh" id="danhgia',$element['Ma_MĐHT'],'" value="',$element['Ma_MĐHT'],'" />',$element['Ten_MĐHT'],'</label><br/>'
                ?>
                <br/>

            <button type="submit">Lưu Đánh giá</button>
        </form>
    </div>
</div>

<script>
jQuery(document).ready(function($) {
    $(".ngaythang").datepicker({dateFormat: 'dd/mm/yy'});
    $("#dot_danh_gia").change(function(event) {
        loadData()
    });
    loadData()
    function loadData() {
        
        dotdanhgia = $("#dot_danh_gia").val();
        canbo_tdgID = <?php echo $canbo_tdgID?>;
        $.ajax({
            url: '<?php echo $this->basePath('manager/canbo/danhgianam'); ?>',
            type: 'POST',
            dataType: 'json',
            data: {canbo_tdgID: canbo_tdgID,dotdanhgia:dotdanhgia},
        })
        .done(function(data) {
            
            if(data[0] != false){
                info = data[0]
                $("#luu_y").val(info['luu_y'])
                $("#noi_dung_danh_gia").val(info['noi_dung_danh_gia'])
                if(info['ma_tu_xep_loai'] != null){
                        $("#tudanhgia"+info['ma_tu_xep_loai']).prop("checked",true);
                        $("#danhgia"+info['ma_xep_loai_finish']).prop("checked",true);
                }
            }else{
                $("#luu_y").val("")
                $("#noi_dung_danh_gia").val("")
                $(".hoanthanh").prop('checked',false);
            }
        }) 
    }
    
});
    
</script>