<div class="block">
    <h2 class="title">Bảng chính</h2>
    <div class="block-content">

        <ul class="metro">

            <li title="Quản lý tài khoản">
                <a href="<?php echo $this->basePath('admin/user'); ?>">
                    Quản lý tài khoàn
                    <span> <i class="fa fa-user fa-5x"></i></span>
                </a>
            </li>

        </ul>
    </div>
</div>
<div class="clear"></div>
<div class="block">
    <h2 class="title">Dữ liệu</h2>
    <div class="block-content">
        <ul class="metro">
            <li title="Sao lưu dữ liệu">
                <a href="<?php echo $this->basePath('backup'); ?>">
                    Sao lưu dữ liệu
                    <span><i class="fa fa-save fa-5x"></i></span>
                </a>
            </li>
        </ul>
    </div>
</div>